server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name=thebetterbank
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10

  main:
    allow-bean-definition-overriding: true

  jackson:
    time-zone: Asia/Seoul # Jackson? ???? ?? ??? ??

  jpa:
    hibernate:
      ddl-auto: update

    # jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # log
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      timeout: 10000

# actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus

  endpoint:
    health:
      show-details: always

  info:
    os:
      enabled: true
    java:
      enabled: true
